const actions = {
    FETCH_BODY_DATA: 'FETCH_BODY_DATA',
    FETCH_BODY_DATA_SUCCESS: 'FETCH_BODY_DATA_SUCCESS',
    FETCH_BODY_DATA_FAIL: 'FETCH_BODY_DATA_FAIL',

    POST_BODY_DATA: 'POST_BODY_DATA',
    POST_BODY_DATA_SUCCESS: 'POST_BODY_DATA_SUCCESS',
    POST_BODY_DATA_FAIL: 'POST_BODY_DATA_FAIL',
}

export default actions