const actions = {
    FETCH_FAVORITES: 'FETCH_FAVORITES',
    FETCH_FAVORITES_SUCCESS: 'FETCH_FAVORITES_SUCCESS',
    FETCH_FAVORITES_FAIL: 'FETCH_FAVORITES_FAIL',

    POST_FAVORITE: 'POST_FAVORITE',
    POST_FAVORITE_SUCCESS: 'POST_FAVORITE_SUCCESS',
    POST_FAVORITE_FAIL: 'POST_FAVORITE_FAIL',

    DELETE_FAVORITE: 'DELETE_FAVORITE',
    DELETE_FAVORITE_SUCCESS: 'DELETE_FAVORITE_SUCCESS',
    DELETE_FAVORITE_FAIL: 'DELETE_FAVORITE_FAIL',
}

export default actions