const actions = {
    FETCH_ROUTINESS: 'FETCH_ROUTINESS',
    FETCH_ROUTINESS_SUCCESS: 'FETCH_ROUTINESS_SUCCESS',
    FETCH_ROUTINESS_FAIL: 'FETCH_ROUTINESS_FAIL',

    POST_ROUTINE: 'POST_ROUTINE',
    POST_ROUTINE_SUCCESS: 'POST_ROUTINE_SUCCESS',
    POST_ROUTINE_FAIL: 'POST_ROUTINE_FAIL',

    DELETE_ROUTINE: 'DELETE_ROUTINE',
    DELETE_ROUTINE_SUCCESS: 'DELETE_ROUTINE_SUCCESS',
    DELETE_ROUTINE_FAIL: 'DELETE_ROUTINE_FAIL',
}

export default actions